# This formula is auto-generated by GoReleaser on release.
# For manual tap setup before first release, use the HEAD-only version below.

class Imggen < Formula
  desc "CLI tool for generating images using AI image generation APIs"
  homepage "https://github.com/manashmandal/imggen"
  license "MIT"
  head "https://github.com/manashmandal/imggen.git", branch: "main"

  # Uncomment and update when first release is created:
  # url "https://github.com/manashmandal/imggen/archive/refs/tags/v0.1.0.tar.gz"
  # sha256 "REPLACE_WITH_SHA256"
  # version "0.1.0"

  depends_on "go" => :build

  def install
    ldflags = %W[
      -s -w
      -X main.version=#{version || "HEAD"}
      -X main.commit=HEAD
    ]
    system "go", "build", *std_go_args(ldflags:), "./cmd/imggen"
  end

  test do
    assert_match "imggen", shell_output("#{bin}/imggen --help")
  end
end
